spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend_db
    username: root
    password: apple
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  issuer: backendMyProject         # JWT 발급자 (예: "myApp")
  secretKey: V3rY$3cUr3K3y#2024    # JWT 토큰을 서명할 때 사용하는 비밀 키
  expirationTime: 3600000          # 토큰의 만료 시간 (밀리초, 1시간)
